services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: "laravel-php"
    volumes:
      - ./src/:/var/www/html
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "laravel-nginx"
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - php
  
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: "laravel-db"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume: